# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
            preserve_default=False,
        ),
    ]
